version: "3.4"

services:
  front-server:
    build: 
      context: ./front
      target: prod
#   volumes:
#     - ./front/:/usr/src/app/
    ports:
      - 5000:5000
    stop_signal: SIGINT
    environment:
      - FLASK_APP=front_server
      - USERS=users-server:5000
      - FLASHCARDS=flashcards-server:8080

  users-server:
    build:
      context: ./users/users_server/
      target: dev
    volumes:
      - ./users/users_server/:/usr/src/app/users_server/
        # ports:
        # - 5000:5000
#   networks:
#     - users_local
#     - front_net
    environment:
      - FLASK_APP=users_server
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=develop
      - DATABASE=users-database
    stop_signal: SIGINT

  users-database:
    build: ./users/database/
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=develop
#   networks:
#     - users_local

  flashcards-server:
    build:
      context: ./flashcards/
      target: prod
#   volumes:
#     - ./flashcards_server:/usr/src/app/flashcards_server
    ports:
      - 8080:8080
#   networks:
#     - flashcards_local
#     - front_net
    stop_signal: SIGINT
#   hostname: flashcards

  flashcards-database:
    image: postgres
    restart: always # ???
    environment:
      - POSTGRES_PASSWORD=descards
      - POSTGRES_USER=flashcards
      - POSTGRES_DB=flashcards
#   networks:
#     - flashcards_local

# flashcards-adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 10000:8080 # port 10000 on host
