version: "3.4"

services:
  front-server:
    build: 
      context: ./front
      target: prod
    volumes:
      - ./front/:/usr/src/app/
    ports:
      - 5000:5000
    stop_signal: SIGINT
    environment:
      - FLASK_APP=front_server
      - USERS=users-server:5000
      - FLASHCARDS=flashcards-server:8080
      - RABBIT=rabbit

  users-server:
    build:
      context: ./users/users_server/
      target: prod
    volumes:
      - ./users/users_server/:/usr/src/app/users_server/
        # ports:
        # - 5000:5000
#   networks:
#     - users_local
#     - front_net
    environment:
      - FLASK_APP=users_server
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=develop
      - DATABASE=users-database
    stop_signal: SIGINT

  users-database:
    build: ./users/database/
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=develop
#   networks:
#     - users_local

  flashcards-server:
    build:
      context: ./flashcards/
      target: prod
#   volumes:
#     - ./flashcards_server:/usr/src/app/flashcards_server
#   ports:
#     - 8080:8080
#   networks:
#     - flashcards_local
#     - front_net
    stop_signal: SIGINT
#   hostname: flashcards

  flashcards-database:
    image: postgres
    restart: always # ???
    environment:
      - POSTGRES_PASSWORD=descards
      - POSTGRES_USER=flashcards
      - POSTGRES_DB=flashcards
    ports:
      - 5432:5432
#   networks:
#     - flashcards_local

  generator:
    build: 
      context: ./generator
      target: prod
    stop_signal: SIGINT

  rabbit:
    image: rabbitmq:3.6.14-management
    ports:
      - 5672:5672
      - 15672:15672
