version: "3"

services:

  server:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    networks:
      - net
    stop_signal: SIGINT
    command: "python /usr/src/app/main.py"

networks:
  net:
    driver: bridge
