version: "3"

services:

  server:
    build: ./front_server/
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    networks:
      - net
    stop_signal: SIGINT
    environment: [FLASK_APP]

networks:
  net:
    driver: bridge
