version: "3"

services:

  server:
    build: ./
    volumes:
      - ./:/usr/src/app
#    networks:
#      - front_net
    stop_signal: SIGINT
    command: "python /usr/src/app/main.py"

  database:
    build: ./database/
    restart: always # ???
    environment: 
      POSTGRES_PASSWORD: example

        # networks:
        #   front_net:
        #     external: true
