version: "3"

services:

  server:
    build: ./users_server
    volumes:
      - ./users_server:/usr/src/app
#    networks:
#      - front_net
    stop_signal: SIGINT
    command: "python /usr/src/app/main.py"

  database:
    build: ./database/
    restart: always # ???
    environment: [POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tests:
    build: ./tests
    volumes:
      - ./tests:/tests
    environment: [POSTGRES_DB]

# networks:
#   front_net:
#     external: true
