version: "3.4"

services:

  server:
    build:
      context: ./users_server
      target: test
    volumes:
      - ./users_server:/usr/src/app/users_server
        # ports:
        # - 5000:5000
    networks:
      - front_net
      - users_local
    environment: [FLASK_APP, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB]
    stop_signal: SIGINT

  database:
    build: ./database/
    restart: always
    environment: [POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB]
    networks:
      - users_local

  adminer:
    image: adminer
    restart: always
    ports:
      - 10001:8080
    networks:
      - users_local


networks:
  front_net:
    external: true
  users_local:
    driver: bridge
